# Generated by Django 2.2.2 on 2019-06-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurukai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yurukai',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
