# Generated by Django 2.2.2 on 2019-06-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurukai', '0002_yurukai_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
